app/dcs/api/s3/s3-compatibility: update with the latest storj.io/gateway/docs/s3-compatibility.md
storj/docs pull request #286
Opened 2023-10-04 15:22 UTC by amwolff

This updates the page with the latest storj.io/gateway/docs/s3-compatibility.md to make it the ground truth and prepare for removal of storj.io/gateway/docs/s3-compatibility.md. It also adds another context for GetBucketLocation from https://github.com/storj/docs/pull/285, superseding this pull request.

2023-10-04 15:40 UTC, amwolff commented
It looks like the exact wording for the LocationConstraint section is still pending an approval, so better not to merge it without an explicit approval from, e.g., @onionjake.

2023-10-04 15:42 UTC, amwolff commented
It looks like the wording for the LocationConstraint section is still pending approval, so better not to merge this without explicit approval from, e.g., @onionjake.

2023-10-04 19:58 UTC, halkyon commented
Do you also want to prepare the change to remove the docs in the gateway repo, so we don't have them in two places any longer?

2023-10-04 23:25 UTC, ferristocrat requested changes

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| ListObjects                                 | Partial | Planned full. See https://github.com/storj/roadmap/issues/20 | See ListObjects section                             |
```suggestion
| ListObjects                                 | Partial | We may support lexicographical ordering in the future.  | See ListObjects section                             |
```

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| ListObjects                                 | Partial | Planned full. See https://github.com/storj/roadmap/issues/20 | See ListObjects section                             |
I think we should get rid of references to https://github.com/storj/roadmap/issues/20

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| ListObjectsV2                               | Partial | Planned full. See https://github.com/storj/roadmap/issues/20 | See ListObjects section                             |
```suggestion
| ListObjectsV2                               | Partial | We may support lexicographical ordering in the future. | See ListObjects section                             |
```

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| ListMultipartUploads                        | Partial | Planned full. See https://github.com/storj/roadmap/issues/20 | See ListMultipartUploads section                    |
```suggestion
| ListMultipartUploads                        | Partial | We may support lexicographical ordering in the future. | See ListMultipartUploads section                    |
```

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| UploadPartCopy                              | No      | Planned. See https://github.com/storj/roadmap/issues/40      |                                                     |
```suggestion
| UploadPartCopy                              | No      | Partial Support Planned. See https://github.com/storj/roadmap/issues/76      |                                                     |
```

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| `global`      | Stored on the entire globe connected to the public network                                                                |
```suggestion
| `global`      | Stored on nodes connected to the global public network                                                                |
```

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +| `global`      | Stored on the entire globe connected to the public network                                                                |
It read a little bit weird. I think this is better, but I'm not SUPER opinionated here.

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +Specifies the placement region where the bucket data is stored:
```suggestion
Specifies the placement region where the object data for a bucket is stored:
```

2023-10-04 23:25 UTC, ferristocrat commented on app/dcs/api/s3/s3-compatibility/page.md
> +Specifies the placement region where the bucket data is stored:
Should we specific OBJECT data? Given that this is grabbed from the satellite, this is more accurate right?

2023-10-05 14:42 UTC, onionjake approved these changes

2023-10-06 10:23 UTC, amwolff commented
I pushed 7400cbd, which fixes the formatting of the tables and consistency of punctuation and capital letters usage after Michael's additions.

2023-10-09 19:54 UTC, onionjake commented
This is good to go as far as I'm concerned. @ferristocrat I think you need to mark it approved because you reviewed with comments?

2023-10-11 14:04 UTC, ferristocrat approved these changes

2023-10-12 09:35 UTC, merged