Rclone improvements
storj/docs pull request #366
Opened 2024-05-01 13:53 UTC by RecRanger

2025-05-20 03:30 UTC, AlexeyALeonov requested changes

2025-05-20 03:30 UTC, AlexeyALeonov commented on app/dcs/third-party-tools/rclone/rclone-s3/page.md
> +
~~~suggestion
{% tabs %}
{% tab label="Windows" %}
```powershell
mkdir ~/mybucket
rclone mount waterbear:mybucket ~/mybucket --vfs-cache-mode full
```
{% /tab %}

{% tab label="Linux" %}

~~~

2025-05-20 03:30 UTC, AlexeyALeonov commented on app/dcs/third-party-tools/rclone/rclone-s3/page.md
> +Use the `mount` command to mount a bucket to a folder (Mac and Linux only). When mounted, you can use the bucket as a local folder.
```suggestion
Use the `mount` command to mount a bucket to a folder (Mac, Windows and Linux) or as a disk drive (Windows). When mounted, you can use the bucket (drive) as a local folder (drive).
```

2025-05-20 03:30 UTC, AlexeyALeonov commented on app/dcs/third-party-tools/rclone/rclone-s3/page.md
> +
~~~suggestion
{% /tab %}

{% tab label="macOS" %}
```shell
sudo mkdir /mnt/mybucket
sudo chown $USER: /mnt/mybucket
rclone mount waterbear:mybucket /mnt/mybucket --vfs-cache-mode full
```
{% /tab %}
{% /tabs %}
~~~

2025-05-20 03:30 UTC, AlexeyALeonov commented on app/dcs/third-party-tools/rclone/rclone-s3/page.md
> +```
~~~suggestion
To unmount the bucket, use the `Ctrl-C` keystroke to stop rclone.
~~~

2025-07-14 15:01 UTC, ifraixedes commented
@AlexeyALeonov does it make sense to try to rebase this and merge it?

2025-07-14 15:10 UTC, AlexeyALeonov commented
> @AlexeyALeonov does it make sense to try to rebase this and merge it?

Perhaps, I just didn't have time to do that

2025-07-15 01:58 UTC, merged